// PorMigrar/components/Sidebar.tsx
import { useState } from 'react';
import {
  LayoutDashboard,
  FileText,
  Pill,
  Users,
  Stethoscope,
  Package,
  AlertTriangle,
  ShieldCheck,
  BarChart3,
  Network,
  Shield,
  FileCheck,
  BookOpen,
  Settings,
  ChevronDown,
  ChevronRight,
  Menu,
  X,
  Bell,
  Receipt,
  UserCog,
  HelpCircle
} from 'lucide-react';
import { Logo } from './Logo';
import { cn } from './ui/utils';

interface MenuItem {
  id: string;
  label: string;
  icon: React.ElementType;
  route: string;
  visible?: boolean;
  subItems?: SubMenuItem[];
}

interface SubMenuItem {
  id: string;
  label: string;
  route: string;
  visible?: boolean;
}

const menuStructure: MenuItem[] = [
  {
    id: 'dashboard',
    label: 'Inicio',
    icon: LayoutDashboard,
    route: '/dashboard',
    visible: true
  },
  {
    id: 'prescripciones',
    label: 'Prescripciones',
    icon: FileText,
    route: '/prescripciones',
    visible: true,
    subItems: [
      { id: 'nueva', label: 'Nueva receta', route: '/prescripciones/nueva', visible: true },
      { id: 'borradores', label: 'Mis borradores', route: '/prescripciones/borradores', visible: true },
      { id: 'emitidas', label: 'Recetas emitidas', route: '/prescripciones/emitidas', visible: true },
      { id: 'buscar', label: 'Buscar receta', route: '/prescripciones/buscar', visible: true },
      { id: 'duplicar', label: 'Duplicar receta', route: '/prescripciones/duplicar', visible: true },
      { id: 'centros', label: 'Centros médicos', route: '/prescripciones/centros', visible: true }
    ]
  },
  {
    id: 'dispensacion',
    label: 'Dispensación',
    icon: Pill,
    route: '/dispensacion',
    visible: true,
    subItems: [
      { id: 'verificar', label: 'Verificar receta (QR/Token)', route: '/dispensacion/verificar', visible: true },
      { id: 'registrar', label: 'Registrar dispensación', route: '/dispensacion/registrar', visible: true },
      { id: 'rechazos', label: 'Rechazos y motivos', route: '/dispensacion/rechazos', visible: true }
    ]
  },
  {
    id: 'pacientes',
    label: 'Pacientes',
    icon: Users,
    route: '/pacientes',
    visible: true,
    subItems: [
      { id: 'lista', label: 'Listado de pacientes', route: '/pacientes/lista', visible: true },
      { id: 'perfil', label: 'Perfil del paciente', route: '/pacientes/perfil', visible: true },
      { id: 'recetas', label: 'Recetas del paciente', route: '/pacientes/recetas', visible: true }
    ]
  },
  {
    id: 'medicos',
    label: 'Médicos',
    icon: Stethoscope,
    route: '/medicos',
    visible: true,
    subItems: [
      { id: 'lista', label: 'Listado de médicos', route: '/medicos/lista', visible: true },
      { id: 'editar', label: 'Alta/Edición de médico', route: '/medicos/editar', visible: true }
    ]
  },
  {
    id: 'inventario',
    label: 'Farmacia e Inventario',
    icon: Package,
    route: '/inventario',
    visible: true,
    subItems: [
      { id: 'stock', label: 'Stock de medicamentos', route: '/inventario/stock', visible: true },
      { id: 'farmacias', label: 'Farmacias registradas', route: '/inventario/farmacias', visible: true },
      { id: 'consulta', label: 'Consulta de inventario', route: '/inventario/consulta', visible: true },
      { id: 'alertas', label: 'Alertas de stock bajo', route: '/inventario/alertas', visible: true },
      { id: 'ajustes', label: 'Ajustes de stock', route: '/inventario/ajustes', visible: true },
      { id: 'lotes', label: 'Lotes y vencimientos', route: '/inventario/lotes', visible: true }
    ]
  },
  {
    id: 'talonarios',
    label: 'Talonarios',
    icon: Receipt,
    route: '/talonarios',
    visible: true,
    subItems: [
      { id: 'comprar', label: 'Comprar talonarios', route: '/talonarios/comprar', visible: true },
      { id: 'listado', label: 'Mis talonarios', route: '/talonarios/listado', visible: true }
    ]
  },
  {
    id: 'alertas',
    label: 'Alertas clínicas (CDS)',
    icon: AlertTriangle,
    route: '/alertas',
    visible: true,
    subItems: [
      { id: 'bandeja', label: 'Bandeja de alertas', route: '/alertas/bandeja', visible: true },
      { id: 'reglas', label: 'Reglas e interacciones', route: '/alertas/reglas', visible: true },
      { id: 'tipos', label: 'Tipos de alertas', route: '/alertas/tipos', visible: true }
    ]
  },
  {
    id: 'firma',
    label: 'Firma y verificación',
    icon: ShieldCheck,
    route: '/firma',
    visible: true,
    subItems: [
      { id: 'firmar', label: 'Firmar receta', route: '/firma/firmar', visible: true },
      { id: 'qr', label: 'Generar/Ver QR', route: '/firma/qr', visible: true },
      { id: 'verificar', label: 'Verificación de QR/Token', route: '/firma/verificar', visible: true },
      { id: 'trazabilidad', label: 'Trazabilidad de firmas', route: '/firma/trazabilidad', visible: true }
    ]
  },
  {
    id: 'reportes',
    label: 'Reportes y analítica',
    icon: BarChart3,
    route: '/reportes',
    visible: true,
    subItems: [
      { id: 'actividad-medico', label: 'Actividad por médico', route: '/reportes/actividad-medico', visible: true },
      { id: 'actividad-farmacia', label: 'Actividad de farmacia', route: '/reportes/actividad-farmacia', visible: true },
      { id: 'exportar', label: 'Exportaciones (CSV/Excel)', route: '/reportes/exportar', visible: true }
    ]
  },
  {
    id: 'interop',
    label: 'Interoperabilidad',
    icon: Network,
    route: '/interop',
    visible: true,
    subItems: [
      { id: 'fhir-ids', label: 'IDs FHIR', route: '/interop/fhir-ids', visible: true },
      { id: 'exportar', label: 'Exportar receta (FHIR)', route: '/interop/exportar', visible: true },
      { id: 'importar', label: 'Importar datos externos', route: '/interop/importar', visible: true },
      { id: 'eventos', label: 'Registro HL7 eventos', route: '/interop/eventos', visible: true }
    ]
  },
  {
    id: 'seguridad',
    label: 'Seguridad y usuarios',
    icon: Shield,
    route: '/seguridad',
    visible: true,
    subItems: [
      { id: 'usuarios', label: 'Usuarios', route: '/seguridad/usuarios', visible: true },
      { id: 'registro', label: 'Registro de usuarios', route: '/seguridad/registro', visible: true },
      { id: 'aprobaciones', label: 'Aprobación de usuarios', route: '/seguridad/aprobaciones', visible: true },
      { id: 'roles', label: 'Roles y permisos', route: '/seguridad/roles', visible: true },
      { id: 'parametros', label: 'Parámetros de seguridad', route: '/seguridad/parametros', visible: true },
      { id: 'bloqueos', label: 'Bloqueos/Desbloqueos', route: '/seguridad/bloqueos', visible: true },
      { id: 'sesiones', label: 'Sesiones de usuario', route: '/seguridad/sesiones', visible: true },
      { id: 'mis-sesiones', label: 'Mis sesiones activas', route: '/seguridad/mis-sesiones', visible: true }
    ]
  },
  {
    id: 'auditoria',
    label: 'Auditoría y cumplimiento',
    icon: FileCheck,
    route: '/auditoria',
    visible: true,
    subItems: [
      { id: 'log', label: 'Log auditoría', route: '/auditoria/log', visible: true }
    ]
  },
  {
    id: 'catalogos',
    label: 'Catálogos clínicos',
    icon: BookOpen,
    route: '/catalogos',
    visible: true,
    subItems: [
      { id: 'medicamentos', label: 'Medicamentos', route: '/catalogos/medicamentos', visible: true },
      { id: 'vias', label: 'Vías de administración', route: '/catalogos/vias', visible: true },
      { id: 'especialidades', label: 'Especialidades', route: '/catalogos/especialidades', visible: true },
      { id: 'unidades', label: 'Unidades médicas', route: '/catalogos/unidades', visible: true },
      { id: 'interacciones', label: 'Interacciones', route: '/catalogos/interacciones', visible: true },
      { id: 'tipos-alertas', label: 'Tipos de alertas', route: '/catalogos/tipos-alertas', visible: true },
      { id: 'paises', label: 'Países', route: '/catalogos/paises', visible: true }
    ]
  },
  {
    id: 'notificaciones',
    label: 'Notificaciones',
    icon: Bell,
    route: '/notificaciones',
    visible: true,
    subItems: [
      { id: 'lista-notificaciones', label: 'Listado de notificaciones', route: '/notificaciones/lista', visible: true },
      { id: 'nueva-notificacion', label: 'Nueva notificación', route: '/notificaciones/nueva', visible: true }
    ]
  },
  {
    id: 'config',
    label: 'Configuración',
    icon: Settings,
    route: '/config',
    visible: true,
    subItems: [
      { id: 'politicas', label: 'Políticas de recetas', route: '/config/politicas', visible: true },
      { id: 'auxiliares', label: 'Catálogos auxiliares', route: '/config/auxiliares', visible: true },
      { id: 'numeracion', label: 'Numeración de recetas', route: '/config/numeracion', visible: true }
    ]
  },
  {
    id: 'ayuda',
    label: 'Centro de Ayuda',
    icon: HelpCircle,
    route: '/ayuda',
    visible: true
  },
  {
    id: 'autoservicio',
    label: 'Autoservicio',
    icon: UserCog,
    route: '/autoservicio',
    visible: true
  },
  {
    id: 'documentacion',
    label: 'Documentación',
    icon: BookOpen,
    route: '/documentacion',
    visible: true
  }
];

interface SidebarProps {
  currentRoute: string;
  onNavigate: (route: string) => void;
  collapsed?: boolean;
  onToggleCollapse?: () => void;
}

export function Sidebar({ currentRoute, onNavigate, collapsed = false, onToggleCollapse }: SidebarProps) {
  const [expandedItems, setExpandedItems] = useState<string[]>(['prescripciones', 'dispensacion']);

  const toggleExpanded = (id: string) => {
    setExpandedItems(prev =>
      prev.includes(id) ? prev.filter(item => item !== id) : [...prev, id]
    );
  };

  const isActive = (route: string) => currentRoute === route;
  const isParentActive = (item: MenuItem) => {
    if (item.route === currentRoute) return true;
    return item.subItems?.some(sub => sub.route === currentRoute) ?? false;
  };

  return (
    <aside
      className={cn(
        'bg-white border-r border-border h-screen flex flex-col transition-all duration-300',
        collapsed ? 'w-16' : 'w-64'
      )}
    >
      {/* Header */}
      <div className="p-4 border-b border-border flex items-center justify-between">
        {!collapsed && <Logo size="sm" />}
        {collapsed && <Logo size="sm" variant="icon" className="mx-auto" />}
        {onToggleCollapse && (
          <button
            onClick={onToggleCollapse}
            className="p-1 hover:bg-accent rounded-md transition-colors"
            aria-label={collapsed ? 'Expandir menú' : 'Contraer menú'}
          >
            {collapsed ? <Menu className="w-4 h-4" /> : <X className="w-4 h-4" />}
          </button>
        )}
      </div>

      {/* Navigation */}
      <nav className="flex-1 overflow-y-auto p-2">
        <ul className="space-y-1">
          {menuStructure.map(item => {
            if (!item.visible) return null;

            const Icon = item.icon;
            const hasSubItems = item.subItems && item.subItems.length > 0;
            const isExpanded = expandedItems.includes(item.id);
            const parentActive = isParentActive(item);

            return (
              <li key={item.id}>
                <button
                  onClick={() => {
                    if (hasSubItems) {
                      toggleExpanded(item.id);
                      if (collapsed && onToggleCollapse) {
                        onToggleCollapse();
                      }
                    } else {
                      onNavigate(item.route);
                    }
                  }}
                  className={cn(
                    'w-full flex items-center gap-3 px-3 py-2 rounded-md transition-colors',
                    parentActive
                      ? 'bg-primary text-primary-foreground'
                      : 'text-sidebar-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground',
                    collapsed && 'justify-center'
                  )}
                  title={collapsed ? item.label : undefined}
                >
                  <Icon className={cn('flex-shrink-0', collapsed ? 'w-5 h-5' : 'w-4 h-4')} />
                  {!collapsed && (
                    <>
                      <span className="flex-1 text-left text-sm">{item.label}</span>
                      {hasSubItems && (
                        isExpanded ? (
                          <ChevronDown className="w-4 h-4" />
                        ) : (
                          <ChevronRight className="w-4 h-4" />
                        )
                      )}
                    </>
                  )}
                </button>

                {/* Submenu */}
                {hasSubItems && isExpanded && !collapsed && (
                  <ul className="mt-1 ml-4 pl-4 border-l-2 border-border space-y-1">
                    {item.subItems!.map(subItem => {
                      if (!subItem.visible) return null;
                      return (
                        <li key={subItem.id}>
                          <button
                            onClick={() => onNavigate(subItem.route)}
                            className={cn(
                              'w-full text-left px-3 py-2 text-sm rounded-md transition-colors',
                              isActive(subItem.route)
                                ? 'bg-secondary text-secondary-foreground'
                                : 'text-muted-foreground hover:bg-accent hover:text-accent-foreground'
                            )}
                          >
                            {subItem.label}
                          </button>
                        </li>
                      );
                    })}
                  </ul>
                )}
              </li>
            );
          })}
        </ul>
      </nav>

      {/* Footer */}
      <div className="p-4 border-t border-border">
        {!collapsed ? (
          <div className="text-xs text-muted-foreground space-y-1">
            <p>Cumplimiento normativo:</p>
            <div className="flex gap-2 flex-wrap">
              <span className="px-2 py-1 bg-accent rounded text-accent-foreground">HL7</span>
              <span className="px-2 py-1 bg-accent rounded text-accent-foreground">FDA</span>
              <span className="px-2 py-1 bg-accent rounded text-accent-foreground">OMS</span>
            </div>
          </div>
        ) : (
          <div className="flex justify-center">
            <ShieldCheck className="w-5 h-5 text-success" />
          </div>
        )}
      </div>
    </aside>
  );
}

// eprescription-frontend/src/app/components/sidebar/sidebar.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { LucideAngularModule, Home, FileText, Users, UserCheck, Building2, Package, BarChart3, Settings, Stethoscope, Activity, ChevronDown, ChevronRight, Pill, Shield, Calendar, Bell, HelpCircle, Receipt, AlertTriangle, ShieldCheck, Network, FileCheck, BookOpen, LayoutDashboard, Menu, X, UserCog } from 'lucide-angular';

interface MenuItem {
  title: string;
  icon: any;
  route?: string;
  children?: MenuItem[];
  badge?: string;
  isExpanded?: boolean;
}

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, RouterModule, LucideAngularModule],
  template: `
    <div [class]="'flex h-full flex-col bg-gradient-to-b from-blue-600 to-blue-700 text-white shadow-xl transition-all duration-300 ' + (isCollapsed ? 'w-16' : 'w-64')">
      <!-- Header -->
      <div class="flex items-center gap-3 px-4 py-5 border-b border-white/20">
        <!-- Hamburger Button -->
        <button 
          (click)="toggleSidebar()"
          class="flex h-8 w-8 items-center justify-center rounded-lg bg-white/20 backdrop-blur-sm hover:bg-white/30 transition-colors"
        >
          <lucide-icon [img]="isCollapsed ? menuIcon : xIcon" class="h-5 w-5 text-white"></lucide-icon>
        </button>
        
        <!-- Logo and Title (hidden when collapsed) -->
        <div *ngIf="!isCollapsed" class="flex items-center gap-3">
          <div class="flex h-8 w-8 items-center justify-center rounded-lg bg-white/20 backdrop-blur-sm">
            <lucide-icon [img]="stethoscopeIcon" class="h-5 w-5 text-white"></lucide-icon>
          </div>
          <div>
            <h1 class="font-bold text-sm">ePrescription</h1>
            <p class="text-xs text-white/80">Sistema Médico</p>
          </div>
        </div>
      </div>

      <!-- Navigation Menu -->
      <nav class="flex-1 space-y-1 px-2 py-4 overflow-y-auto">
        <div *ngFor="let item of menuItems" class="space-y-1">
          <!-- Menu Item with Children (Accordion) -->
          <div *ngIf="item.children && item.children.length > 0">
            <button
              (click)="toggleExpanded(item)"
              [class]="'w-full flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition-all duration-200 group text-white/80 hover:bg-white/10 hover:text-white hover:shadow-md ' + (isCollapsed ? 'justify-center' : '')"
              [title]="isCollapsed ? item.title : ''"
            >
              <lucide-icon [img]="item.icon" class="h-5 w-5 transition-transform group-hover:scale-110 flex-shrink-0"></lucide-icon>
              <span *ngIf="!isCollapsed" class="font-medium flex-1 text-left">{{ item.title }}</span>
              <span *ngIf="item.badge && !isCollapsed" class="bg-red-500 text-white text-xs px-2 py-0.5 rounded-full">{{ item.badge }}</span>
              <span *ngIf="item.badge && isCollapsed" class="absolute -top-1 -right-1 bg-red-500 text-white text-xs w-5 h-5 rounded-full flex items-center justify-center">{{ item.badge }}</span>
              <lucide-icon 
                *ngIf="!isCollapsed"
                [img]="item.isExpanded ? chevronDownIcon : chevronRightIcon" 
                class="h-4 w-4 transition-transform duration-200">
              </lucide-icon>
            </button>
            
            <!-- Submenu (only show when not collapsed and expanded) -->
            <div 
              *ngIf="item.isExpanded && !isCollapsed" 
              class="ml-4 mt-1 space-y-1 border-l border-white/20 pl-4"
            >
              <a
                *ngFor="let child of item.children"
                [routerLink]="child.route"
                routerLinkActive="bg-white/20 text-white shadow-lg backdrop-blur-sm border border-white/30"
                class="flex items-center gap-3 rounded-lg px-3 py-2 text-sm transition-all duration-200 group text-white/70 hover:bg-white/10 hover:text-white"
              >
                <lucide-icon [img]="child.icon" class="h-4 w-4 transition-transform group-hover:scale-110"></lucide-icon>
                <span class="font-medium">{{ child.title }}</span>
                <span *ngIf="child.badge" class="bg-orange-500 text-white text-xs px-1.5 py-0.5 rounded-full">{{ child.badge }}</span>
              </a>
            </div>
          </div>

          <!-- Simple Menu Item -->
          <a
            *ngIf="!item.children || item.children.length === 0"
            [routerLink]="item.route"
            routerLinkActive="bg-white/20 text-white shadow-lg backdrop-blur-sm border border-white/30"
            [class]="'flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition-all duration-200 group text-white/80 hover:bg-white/10 hover:text-white hover:shadow-md relative ' + (isCollapsed ? 'justify-center' : '')"
            [title]="isCollapsed ? item.title : ''"
          >
            <lucide-icon [img]="item.icon" class="h-5 w-5 transition-transform group-hover:scale-110 flex-shrink-0"></lucide-icon>
            <span *ngIf="!isCollapsed" class="font-medium">{{ item.title }}</span>
            <span *ngIf="item.badge && !isCollapsed" class="bg-red-500 text-white text-xs px-2 py-0.5 rounded-full ml-auto">{{ item.badge }}</span>
            <span *ngIf="item.badge && isCollapsed" class="absolute -top-1 -right-1 bg-red-500 text-white text-xs w-5 h-5 rounded-full flex items-center justify-center">{{ item.badge }}</span>
          </a>
        </div>
      </nav>
      
      <!-- Footer -->
      <div class="px-4 py-4 border-t border-white/20">
        <div *ngIf="!isCollapsed" class="text-xs text-white/60 text-center">
          <p>Cumplimiento normativo:</p>
          <div class="flex justify-center gap-2 mt-1">
            <span class="bg-white/20 px-2 py-1 rounded text-xs">HL7</span>
            <span class="bg-white/20 px-2 py-1 rounded text-xs">FDA</span>
            <span class="bg-white/20 px-2 py-1 rounded text-xs">OMS</span>
          </div>
        </div>
        <div *ngIf="isCollapsed" class="flex justify-center">
          <div class="w-8 h-8 bg-white/20 rounded-lg flex items-center justify-center">
            <lucide-icon [img]="shieldCheckIcon" class="h-4 w-4 text-white/60"></lucide-icon>
          </div>
        </div>
      </div>
    </div>
  `
})
export class SidebarComponent {
  // Sidebar state
  isCollapsed = false;

  // Icons
  homeIcon = Home;
  layoutDashboardIcon = LayoutDashboard;
  fileTextIcon = FileText;
  usersIcon = Users;
  userCheckIcon = UserCheck;
  building2Icon = Building2;
  packageIcon = Package;
  barChart3Icon = BarChart3;
  settingsIcon = Settings;
  stethoscopeIcon = Stethoscope;
  activityIcon = Activity;
  chevronDownIcon = ChevronDown;
  chevronRightIcon = ChevronRight;
  pillIcon = Pill;
  shieldIcon = Shield;
  calendarIcon = Calendar;
  bellIcon = Bell;
  helpCircleIcon = HelpCircle;
  receiptIcon = Receipt;
  alertTriangleIcon = AlertTriangle;
  shieldCheckIcon = ShieldCheck;
  networkIcon = Network;
  fileCheckIcon = FileCheck;
  bookOpenIcon = BookOpen;
  menuIcon = Menu;
  xIcon = X;
  userCogIcon = UserCog;

  menuItems: MenuItem[] = [
    {
      title: 'Inicio',
      icon: this.layoutDashboardIcon,
      route: '/dashboard'
    },
    {
      title: 'Prescripciones',
      icon: this.fileTextIcon,
      isExpanded: false,
      children: [
        { title: 'Nueva receta', icon: this.fileTextIcon, route: '/prescripciones/nueva' },
        { title: 'Mis borradores', icon: this.fileTextIcon, route: '/prescripciones/borradores' },
        { title: 'Recetas emitidas', icon: this.fileTextIcon, route: '/prescripciones/emitidas' },
        { title: 'Buscar receta', icon: this.fileTextIcon, route: '/prescripciones/buscar' },
        { title: 'Duplicar receta', icon: this.fileTextIcon, route: '/prescripciones/duplicar' },
        { title: 'Centros médicos', icon: this.building2Icon, route: '/prescripciones/centros' }
      ]
    },
    {
      title: 'Dispensación',
      icon: this.pillIcon,
      isExpanded: false,
      children: [
        { title: 'Verificar receta (QR/Token)', icon: this.shieldCheckIcon, route: '/dispensacion/verificar' },
        { title: 'Registrar dispensación', icon: this.pillIcon, route: '/dispensacion/registrar' },
        { title: 'Rechazos y motivos', icon: this.alertTriangleIcon, route: '/dispensacion/rechazos' }
      ]
    },
    {
      title: 'Pacientes',
      icon: this.usersIcon,
      isExpanded: false,
      children: [
        { title: 'Listado de pacientes', icon: this.usersIcon, route: '/pacientes/lista' },
        { title: 'Perfil del paciente', icon: this.userCheckIcon, route: '/pacientes/perfil' },
        { title: 'Recetas del paciente', icon: this.fileTextIcon, route: '/pacientes/recetas' }
      ]
    },
    {
      title: 'Médicos',
      icon: this.stethoscopeIcon,
      isExpanded: false,
      children: [
        { title: 'Listado de médicos', icon: this.stethoscopeIcon, route: '/medicos/lista' },
        { title: 'Alta/Edición de médico', icon: this.userCheckIcon, route: '/medicos/editar' }
      ]
    },
    {
      title: 'Farmacia e Inventario',
      icon: this.packageIcon,
      isExpanded: false,
      children: [
        { title: 'Stock de medicamentos', icon: this.packageIcon, route: '/inventario/stock' },
        { title: 'Farmacias registradas', icon: this.building2Icon, route: '/inventario/farmacias' },
        { title: 'Consulta de inventario', icon: this.packageIcon, route: '/inventario/consulta' },
        { title: 'Alertas de stock bajo', icon: this.alertTriangleIcon, route: '/inventario/alertas', badge: '3' },
        { title: 'Ajustes de stock', icon: this.settingsIcon, route: '/inventario/ajustes' },
        { title: 'Lotes y vencimientos', icon: this.calendarIcon, route: '/inventario/lotes' }
      ]
    },
    {
      title: 'Talonarios',
      icon: this.receiptIcon,
      isExpanded: false,
      children: [
        { title: 'Comprar talonarios', icon: this.receiptIcon, route: '/talonarios/comprar' },
        { title: 'Mis talonarios', icon: this.receiptIcon, route: '/talonarios/listado' }
      ]
    },
    {
      title: 'Alertas clínicas (CDS)',
      icon: this.alertTriangleIcon,
      isExpanded: false,
      children: [
        { title: 'Bandeja de alertas', icon: this.bellIcon, route: '/alertas/bandeja' },
        { title: 'Reglas e interacciones', icon: this.settingsIcon, route: '/alertas/reglas' },
        { title: 'Tipos de alertas', icon: this.alertTriangleIcon, route: '/alertas/configuracion' }
      ]
    },
    {
      title: 'Firma y verificación',
      icon: this.shieldCheckIcon,
      isExpanded: false,
      children: [
        { title: 'Firmar receta', icon: this.shieldCheckIcon, route: '/firma/firmar-receta' },
        { title: 'Generar/Ver QR', icon: this.shieldCheckIcon, route: '/firma/generar-qr' },
        { title: 'Verificación de QR/Token', icon: this.shieldCheckIcon, route: '/firma/verificar-qr' },
        { title: 'Trazabilidad de firmas', icon: this.fileCheckIcon, route: '/firma/trazabilidad' }
      ]
    },
    {
      title: 'Reportes y analítica',
      icon: this.barChart3Icon,
      isExpanded: false,
      children: [
        { title: 'Actividad por médico', icon: this.stethoscopeIcon, route: '/reportes/actividad-medico' },
        { title: 'Actividad de farmacia', icon: this.building2Icon, route: '/reportes/actividad-farmacia' },
        { title: 'Exportaciones (CSV/Excel)', icon: this.fileCheckIcon, route: '/reportes/exportar' }
      ]
    },
    {
      title: 'Interoperabilidad',
      icon: this.networkIcon,
      isExpanded: false,
      children: [
        { title: 'IDs FHIR', icon: this.networkIcon, route: '/interop/fhir-ids' },
        { title: 'Exportar receta (FHIR)', icon: this.fileCheckIcon, route: '/interop/exportar' },
        { title: 'Importar datos externos', icon: this.networkIcon, route: '/interop/importar' },
        { title: 'Registro HL7 eventos', icon: this.fileCheckIcon, route: '/interop/eventos' }
      ]
    },
    {
      title: 'Seguridad y usuarios',
      icon: this.shieldIcon,
      isExpanded: false,
      children: [
        { title: 'Usuarios', icon: this.usersIcon, route: '/seguridad/usuarios' },
        { title: 'Registro de usuarios', icon: this.userCheckIcon, route: '/seguridad/usuarios/registro' },
        { title: 'Aprobación de usuarios', icon: this.shieldCheckIcon, route: '/seguridad/aprobaciones' },
        { title: 'Roles y permisos', icon: this.shieldIcon, route: '/seguridad/roles' },
        { title: 'Parámetros de seguridad', icon: this.settingsIcon, route: '/seguridad/parametros' },
        { title: 'Bloqueos/Desbloqueos', icon: this.alertTriangleIcon, route: '/seguridad/bloqueos' },
        { title: 'Sesiones de usuario', icon: this.activityIcon, route: '/seguridad/sesiones' },
        { title: 'Mis sesiones activas', icon: this.activityIcon, route: '/seguridad/mis-sesiones' }
      ]
    },
    {
      title: 'Auditoría y cumplimiento',
      icon: this.fileCheckIcon,
      isExpanded: false,
      children: [
        { title: 'Log auditoría', icon: this.fileCheckIcon, route: '/auditoria/log-auditoria' }
      ]
    },
    {
      title: 'Catálogos clínicos',
      icon: this.bookOpenIcon,
      isExpanded: false,
      children: [
        { title: 'Medicamentos', icon: this.pillIcon, route: '/catalogos/medicamentos' },
        { title: 'Vías de administración', icon: this.settingsIcon, route: '/catalogos/vias' },
        { title: 'Especialidades', icon: this.stethoscopeIcon, route: '/catalogos/especialidades' },
        { title: 'Unidades médicas', icon: this.building2Icon, route: '/catalogos/unidades' },
        { title: 'Interacciones', icon: this.alertTriangleIcon, route: '/catalogos/interacciones' },
        { title: 'Tipos de alertas', icon: this.bellIcon, route: '/catalogos/tipos-alertas' },
        { title: 'Países', icon: this.homeIcon, route: '/catalogos/paises' }
      ]
    },
    {
      title: 'Notificaciones',
      icon: this.bellIcon,
      isExpanded: false,
      children: [
        { title: 'Listado de notificaciones', icon: this.bellIcon, route: '/notificaciones/lista' },
        { title: 'Nueva notificación', icon: this.bellIcon, route: '/notificaciones/nueva' }
      ]
    },
    {
      title: 'Configuración',
      icon: this.settingsIcon,
      isExpanded: false,
      children: [
        { title: 'Políticas de recetas', icon: this.fileTextIcon, route: '/config/politicas' },
        { title: 'Catálogos auxiliares', icon: this.bookOpenIcon, route: '/config/auxiliares' },
        { title: 'Numeración de recetas', icon: this.settingsIcon, route: '/config/numeracion' }
      ]
    },
    {
      title: 'Ayuda',
      icon: this.helpCircleIcon,
      route: '/ayuda'
    },
    {
      title: 'Autoservicio',
      icon: this.userCogIcon,
      route: '/autoservicio'
    },
    {
      title: 'Documentación',
      icon: this.bookOpenIcon,
      route: '/documentacion'
    }

  ];

  toggleExpanded(item: MenuItem) {
    // Si está colapsado, no permitir expandir submenús
    if (this.isCollapsed) {
      return;
    }

    item.isExpanded = !item.isExpanded;

    // Opcional: cerrar otros acordeones cuando se abre uno
    // this.menuItems.forEach(menuItem => {
    //   if (menuItem !== item && menuItem.children) {
    //     menuItem.isExpanded = false;
    //   }
    // });
  }

  toggleSidebar() {
    this.isCollapsed = !this.isCollapsed;

    // Cerrar todos los submenús cuando se colapsa
    if (this.isCollapsed) {
      this.menuItems.forEach(item => {
        if (item.children) {
          item.isExpanded = false;
        }
      });
    }
  }
}
