// eprescription-frontend/src/app/components/doctor-detail-panel/doctor-detail-panel.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule } from 'lucide-angular';
import { Doctor } from '../../interfaces/doctor.interface';

@Component({
  selector: 'app-doctor-detail-panel',
  standalone: true,
  imports: [
    CommonModule,
    LucideAngularModule
  ],
  templateUrl: './doctor-detail-panel.component.html',
  styleUrls: ['./doctor-detail-panel.component.css']
})
export class DoctorDetailPanelComponent implements OnInit, OnDestroy {
  @Input() doctor: Doctor | null = null;
  @Input() isVisible: boolean = false;
  @Output() close = new EventEmitter<void>();

  ngOnInit() {
    // Handle escape key to close panel
    document.addEventListener('keydown', this.handleEscapeKey.bind(this));
  }

  ngOnDestroy() {
    document.removeEventListener('keydown', this.handleEscapeKey.bind(this));
  }

  private handleEscapeKey(event: KeyboardEvent) {
    if (event.key === 'Escape' && this.isVisible) {
      this.closePanel();
    }
  }

  closePanel() {
    this.close.emit();
  }

  getStatusColor(status: string): string {
    switch (status) {
      case 'active':
        return 'text-green-600 bg-green-100';
      case 'inactive':
        return 'text-red-600 bg-red-100';
      default:
        return 'text-gray-600 bg-gray-100';
    }
  }

  getCertificationStatusColor(status: string): string {
    switch (status) {
      case 'verified':
        return 'text-green-600 bg-green-100';
      case 'expired':
        return 'text-red-600 bg-red-100';
      case 'pending':
        return 'text-yellow-600 bg-yellow-100';
      default:
        return 'text-gray-600 bg-gray-100';
    }
  }

  getCertificationStatusIcon(status: string): string {
    switch (status) {
      case 'verified':
        return 'check-circle';
      case 'expired':
        return 'x-circle';
      case 'pending':
        return 'alert-circle';
      default:
        return 'alert-circle';
    }
  }

  formatDate(dateString: string): string {
    const date = new Date(dateString);
    return date.toLocaleDateString('es-ES', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  }

  formatDateTime(dateString: string): string {
    const date = new Date(dateString);
    return date.toLocaleDateString('es-ES', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  }

  getInitials(fullName: string): string {
    return fullName
      .split(' ')
      .map(name => name.charAt(0))
      .join('')
      .substring(0, 2)
      .toUpperCase();
  }

  isLicenseExpiringSoon(expiryDate: string): boolean {
    const expiry = new Date(expiryDate.split('/').reverse().join('-'));
    const threeMonthsFromNow = new Date();
    threeMonthsFromNow.setMonth(threeMonthsFromNow.getMonth() + 3);
    return expiry <= threeMonthsFromNow;
  }

  editDoctor(): void {
    if (this.doctor) {
      // Emit event to parent component to handle navigation
      // For now, we'll just close the panel
      this.closePanel();
    }
  }

  viewPrescriptions(): void {
    if (this.doctor) {
      // Emit event to parent component to handle navigation to prescriptions
      // For now, we'll just close the panel
      this.closePanel();
    }
  }
}
<!-- Modal lateral derecho para detalles de médico -->
<div 
  *ngIf="isVisible && doctor"
  class="fixed inset-0 z-50 overflow-hidden"
  (click)="closePanel()"
>
  <!-- Overlay -->
  <div class="absolute inset-0 bg-black bg-opacity-50"></div>
  
  <!-- Panel lateral -->
  <div class="absolute right-0 top-0 h-full w-full max-w-md bg-white shadow-xl transform transition-transform duration-300 ease-in-out flex flex-col"
       (click)="$event.stopPropagation()">
    
    <!-- Header del modal -->
    <div class="bg-gradient-to-r from-blue-600 to-blue-700 px-6 py-4 text-white flex-shrink-0">
      <div class="flex items-center justify-between">
        <div>
          <div class="flex items-center gap-2">
            <lucide-icon name="stethoscope" class="w-5 h-5"></lucide-icon>
            <h2 class="text-lg font-semibold">Información del Médico</h2>
          </div>
          <p class="text-blue-100 text-sm mt-1">{{ doctor.licenseNumber }}</p>
        </div>
        <button 
          (click)="closePanel()"
          class="p-2 hover:bg-white/20 rounded-lg transition-colors"
        >
          <lucide-icon name="x" class="w-5 h-5"></lucide-icon>
        </button>
      </div>
    </div>

    <!-- Contenido del modal con scroll -->
    <div class="flex-1 overflow-y-auto">
      <div class="p-6 space-y-6">
      
      <!-- Estado del médico -->
      <div class="bg-gray-50 rounded-lg p-4">
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-2">
            <lucide-icon name="activity" class="w-4 h-4 text-gray-600"></lucide-icon>
            <span class="text-sm font-medium text-gray-700">Estado del médico</span>
          </div>
          <div class="flex items-center gap-2">
            <span [class]="getStatusColor(doctor.status)" class="px-3 py-1 text-xs font-semibold rounded-full">
              {{ doctor.status === 'active' ? 'Activo' : 'Inactivo' }}
            </span>
            <span *ngIf="doctor.isOnDuty" class="px-3 py-1 bg-green-100 text-green-800 text-xs font-semibold rounded-full">
              En turno
            </span>
          </div>
        </div>
        <div class="mt-2 flex items-center gap-2">
          <ng-container [ngSwitch]="doctor.certificationStatus">
            <lucide-icon 
              *ngSwitchCase="'verified'" 
              name="check-circle" 
              class="w-4 h-4 text-green-600"
            ></lucide-icon>
            <lucide-icon 
              *ngSwitchCase="'expired'" 
              name="x-circle" 
              class="w-4 h-4 text-red-600"
            ></lucide-icon>
            <lucide-icon 
              *ngSwitchDefault 
              name="alert-circle" 
              class="w-4 h-4 text-yellow-600"
            ></lucide-icon>
          </ng-container>
          <span class="text-xs text-gray-600">
            Certificación: {{ doctor.certificationStatus === 'verified' ? 'Verificada' : 
                             doctor.certificationStatus === 'expired' ? 'Expirada' : 'Pendiente' }}
          </span>
        </div>
      </div>

      <!-- Información Personal -->
      <div>
        <div class="flex items-center gap-2 mb-3">
          <lucide-icon name="user" class="w-5 h-5 text-gray-600"></lucide-icon>
          <h3 class="text-lg font-semibold text-gray-900">Información Personal</h3>
        </div>
        
        <div class="bg-gray-50 rounded-lg p-4 space-y-3">
          <div>
            <p class="text-sm text-gray-600">Nombre completo</p>
            <p class="font-semibold text-gray-900">{{ doctor.fullName }}</p>
          </div>
          
          <div class="grid grid-cols-2 gap-4">
            <div>
              <p class="text-xs text-gray-600">Email</p>
              <p class="text-sm font-medium text-gray-900">{{ doctor.email }}</p>
            </div>
            <div>
              <p class="text-xs text-gray-600">Teléfono</p>
              <p class="text-sm font-medium text-gray-900">{{ doctor.phone }}</p>
            </div>
          </div>
          
          <div *ngIf="doctor.officePhone">
            <p class="text-xs text-gray-600">Teléfono de oficina</p>
            <p class="text-sm font-medium text-gray-900">{{ doctor.officePhone }}</p>
          </div>
          
          <div>
            <p class="text-xs text-gray-600">Dirección</p>
            <p class="text-sm font-medium text-gray-900">{{ doctor.address }}</p>
            <p class="text-xs text-gray-500">{{ doctor.city }}, {{ doctor.country }}</p>
          </div>
        </div>
      </div>

      <!-- Información Profesional -->
      <div>
        <div class="flex items-center gap-2 mb-3">
          <lucide-icon name="graduation-cap" class="w-5 h-5 text-gray-600"></lucide-icon>
          <h3 class="text-lg font-semibold text-gray-900">Información Profesional</h3>
        </div>
        
        <div class="bg-gray-50 rounded-lg p-4 space-y-3">
          <div>
            <p class="text-sm text-gray-600">Especialidad principal</p>
            <p class="font-semibold text-gray-900">{{ doctor.specialty }}</p>
          </div>
          
          <div *ngIf="doctor.subspecialties.length > 0">
            <p class="text-sm text-gray-600 mb-2">Subespecialidades</p>
            <div class="flex flex-wrap gap-1">
              <span 
                *ngFor="let subspecialty of doctor.subspecialties" 
                class="px-2 py-1 bg-blue-100 text-blue-700 rounded-full text-xs font-medium"
              >
                {{ subspecialty }}
              </span>
            </div>
          </div>
          
          <div class="grid grid-cols-2 gap-4">
            <div>
              <p class="text-xs text-gray-600">Licencia médica</p>
              <p class="text-sm font-medium text-gray-900">{{ doctor.licenseNumber }}</p>
              <p *ngIf="isLicenseExpiringSoon(doctor.licenseExpiry)" class="text-xs text-red-600 font-medium">Por vencer</p>
            </div>
            <div>
              <p class="text-xs text-gray-600">Vencimiento</p>
              <p class="text-sm font-medium text-gray-900">{{ doctor.licenseExpiry }}</p>
            </div>
          </div>
          
          <div>
            <p class="text-xs text-gray-600">Universidad</p>
            <p class="text-sm font-medium text-gray-900">{{ doctor.university }}</p>
          </div>
          
          <div class="grid grid-cols-2 gap-4">
            <div>
              <p class="text-xs text-gray-600">Año graduación</p>
              <p class="text-sm font-medium text-gray-900">{{ doctor.graduationYear }}</p>
            </div>
            <div>
              <p class="text-xs text-gray-600">Experiencia</p>
              <p class="text-sm font-medium text-gray-900">{{ doctor.yearsOfExperience }} años</p>
            </div>
          </div>
        </div>
      </div>

      <!-- Certificaciones -->
      <div *ngIf="doctor.certifications.length > 0">
        <div class="flex items-center gap-2 mb-3">
          <lucide-icon name="award" class="w-5 h-5 text-gray-600"></lucide-icon>
          <h3 class="text-lg font-semibold text-gray-900">Certificaciones</h3>
        </div>
        
        <div class="space-y-2">
          <div 
            *ngFor="let certification of doctor.certifications" 
            class="bg-gray-50 rounded-lg p-3 border-l-4 border-l-blue-500"
          >
            <div class="flex items-center gap-2">
              <lucide-icon name="award" class="w-4 h-4 text-blue-600"></lucide-icon>
              <span class="text-sm font-medium text-gray-900">{{ certification }}</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Horarios de Atención -->
      <div *ngIf="doctor.schedule.length > 0">
        <div class="flex items-center gap-2 mb-3">
          <lucide-icon name="clock" class="w-5 h-5 text-gray-600"></lucide-icon>
          <h3 class="text-lg font-semibold text-gray-900">Horarios de Atención</h3>
        </div>
        
        <div class="space-y-2">
          <div 
            *ngFor="let schedule of doctor.schedule" 
            class="bg-gray-50 rounded-lg p-3"
          >
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-2">
                <lucide-icon name="calendar" class="w-4 h-4 text-gray-600"></lucide-icon>
                <span class="text-sm font-medium text-gray-900">{{ schedule.days }}</span>
              </div>
              <span class="text-sm text-gray-600">{{ schedule.hours }}</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Estadísticas de Actividad -->
      <div>
        <div class="flex items-center gap-2 mb-3">
          <lucide-icon name="trending-up" class="w-5 h-5 text-gray-600"></lucide-icon>
          <h3 class="text-lg font-semibold text-gray-900">Estadísticas de Actividad</h3>
        </div>
        
        <div class="grid grid-cols-2 gap-3">
          <div class="bg-gray-50 rounded-lg p-4 border-l-4 border-l-blue-500">
            <div class="flex items-center justify-between">
              <div>
                <p class="text-xs text-gray-600">Recetas totales</p>
                <p class="text-lg font-bold text-gray-900">{{ doctor.totalPrescriptions }}</p>
              </div>
              <lucide-icon name="file-text" class="w-6 h-6 text-blue-600"></lucide-icon>
            </div>
          </div>
          
          <div class="bg-gray-50 rounded-lg p-4 border-l-4 border-l-green-500">
            <div class="flex items-center justify-between">
              <div>
                <p class="text-xs text-gray-600">Este mes</p>
                <p class="text-lg font-bold text-gray-900">{{ doctor.monthlyPrescriptions }}</p>
              </div>
              <lucide-icon name="activity" class="w-6 h-6 text-green-600"></lucide-icon>
            </div>
          </div>
          
          <div class="bg-gray-50 rounded-lg p-4 border-l-4 border-l-purple-500">
            <div class="flex items-center justify-between">
              <div>
                <p class="text-xs text-gray-600">Pacientes</p>
                <p class="text-lg font-bold text-gray-900">{{ doctor.totalPatients }}</p>
              </div>
              <lucide-icon name="users" class="w-6 h-6 text-purple-600"></lucide-icon>
            </div>
          </div>
          
          <div class="bg-gray-50 rounded-lg p-4 border-l-4 border-l-orange-500">
            <div class="flex items-center justify-between">
              <div>
                <p class="text-xs text-gray-600">Promedio mensual</p>
                <p class="text-lg font-bold text-gray-900">{{ doctor.averageMonthlyPrescriptions }}</p>
              </div>
              <lucide-icon name="trending-up" class="w-6 h-6 text-orange-600"></lucide-icon>
            </div>
          </div>
        </div>
      </div>

      <!-- Fechas -->
      <div class="grid grid-cols-2 gap-4">
        <div class="bg-gray-50 rounded-lg p-4">
          <div class="flex items-center gap-2 mb-2">
            <lucide-icon name="calendar" class="w-4 h-4 text-gray-600"></lucide-icon>
            <span class="text-sm font-medium text-gray-700">Fecha de registro</span>
          </div>
          <p class="text-sm text-gray-900">{{ formatDate(doctor.registrationDate) }}</p>
        </div>
        
        <div class="bg-gray-50 rounded-lg p-4">
          <div class="flex items-center gap-2 mb-2">
            <lucide-icon name="activity" class="w-4 h-4 text-gray-600"></lucide-icon>
            <span class="text-sm font-medium text-gray-700">Última actividad</span>
          </div>
          <p class="text-sm text-gray-900">{{ formatDateTime(doctor.lastActivity) }}</p>
        </div>
      </div>
      
      <!-- Notas -->
      <div *ngIf="doctor.notes" class="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
        <div class="flex items-center gap-2 mb-2">
          <lucide-icon name="file-text" class="w-4 h-4 text-yellow-600"></lucide-icon>
          <span class="text-sm font-medium text-yellow-800">Notas</span>
        </div>
        <p class="text-sm text-yellow-700">{{ doctor.notes }}</p>
      </div>
      </div>
    </div>

    <!-- Footer con botones de acción -->
    <div class="border-t border-gray-200 px-6 py-4 bg-gray-50 space-y-3 flex-shrink-0">
      <button 
        (click)="editDoctor()"
        class="w-full bg-blue-600 hover:bg-blue-700 text-white font-medium py-3 px-4 rounded-lg transition-colors flex items-center justify-center gap-2"
      >
        <lucide-icon name="edit" class="w-4 h-4"></lucide-icon>
        Editar información
      </button>
      
      <button 
        (click)="viewPrescriptions()"
        class="w-full bg-green-600 hover:bg-green-700 text-white font-medium py-3 px-4 rounded-lg transition-colors flex items-center justify-center gap-2"
      >
        <lucide-icon name="file-text" class="w-4 h-4"></lucide-icon>
        Ver recetas emitidas
      </button>
    </div>
  </div>
</div>

// ePrescription-react/src/components/DoctorDetailPanel.tsx
import { useState } from "react";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "./ui/sheet";
import { Button } from "./ui/button";
import { Badge } from "./ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";
import { Separator } from "./ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs";
import { EditDoctorDialog } from "./EditDoctorDialog";
import {
  Stethoscope,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Award,
  GraduationCap,
  FileText,
  Shield,
  Activity,
  Clock,
  Edit,
  UserX,
  CheckCircle2,
  AlertTriangle,
  Building2,
  Briefcase,
  Users,
  TrendingUp,
  BarChart3,
  ClipboardList
} from "lucide-react";

interface DoctorDetailPanelProps {
  doctor: any;
  isOpen: boolean;
  onClose: () => void;
  onEdit?: (id: string) => void;
  onViewPrescriptions?: (doctorId: string) => void;
}

export function DoctorDetailPanel({ doctor, isOpen, onClose, onEdit, onViewPrescriptions }: DoctorDetailPanelProps) {
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);

  if (!doctor) return null;

  const stats = [
    { label: "Recetas emitidas", value: doctor.totalPrescriptions || 0, icon: FileText, color: "text-blue-600" },
    { label: "Pacientes atendidos", value: doctor.totalPatients || 0, icon: Users, color: "text-green-600" },
    { label: "Este mes", value: doctor.monthlyPrescriptions || 0, icon: TrendingUp, color: "text-purple-600" },
  ];

  return (
    <Sheet open={isOpen} onOpenChange={onClose}>
      <SheetContent side="right" className="w-full sm:max-w-2xl overflow-y-auto">
        <SheetHeader className="space-y-4">
          <SheetTitle className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-full bg-blue-100 flex items-center justify-center">
              <Stethoscope className="w-6 h-6 text-blue-600" />
            </div>
            <div>
              <h2 className="text-xl">{doctor.fullName}</h2>
              <p className="text-sm text-muted-foreground">{doctor.specialty}</p>
            </div>
          </SheetTitle>

          {/* Estado del médico */}
          <div className="flex items-center gap-2">
            <Badge
              variant={doctor.status === "active" ? "default" : "secondary"}
              className={
                doctor.status === "active"
                  ? "bg-green-100 text-green-800 border-green-300"
                  : "bg-gray-100 text-gray-800 border-gray-300"
              }
            >
              {doctor.status === "active" ? (
                <>
                  <CheckCircle2 className="w-3 h-3 mr-1" />
                  Activo
                </>
              ) : (
                <>
                  <UserX className="w-3 h-3 mr-1" />
                  Inactivo
                </>
              )}
            </Badge>

            {doctor.certificationStatus === "verified" && (
              <Badge className="bg-blue-100 text-blue-800 border-blue-300">
                <Shield className="w-3 h-3 mr-1" />
                Certificado verificado
              </Badge>
            )}

            {doctor.isOnDuty && (
              <Badge className="bg-green-100 text-green-800 border-green-300">
                <Activity className="w-3 h-3 mr-1" />
                En turno
              </Badge>
            )}
          </div>

          {/* Estadísticas rápidas */}
          <div className="grid grid-cols-3 gap-3">
            {stats.map((stat, index) => (
              <Card key={index}>
                <CardContent className="p-3">
                  <div className="flex flex-col items-center text-center">
                    <stat.icon className={`w-5 h-5 ${stat.color} mb-1`} />
                    <p className="text-xs text-muted-foreground">{stat.label}</p>
                    <p className="text-lg mt-1">{stat.value}</p>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </SheetHeader>

        <Separator className="my-6" />

        <Tabs defaultValue="general" className="w-full">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="general">General</TabsTrigger>
            <TabsTrigger value="professional">Profesional</TabsTrigger>
            <TabsTrigger value="activity">Actividad</TabsTrigger>
          </TabsList>

          {/* Tab General */}
          <TabsContent value="general" className="space-y-4 mt-4">
            {/* Información de contacto */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Phone className="w-4 h-4" />
                  Información de contacto
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="flex items-start gap-3">
                  <Mail className="w-4 h-4 text-muted-foreground mt-1" />
                  <div>
                    <p className="text-xs text-muted-foreground">Email</p>
                    <p className="text-sm">{doctor.email}</p>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <Phone className="w-4 h-4 text-muted-foreground mt-1" />
                  <div>
                    <p className="text-xs text-muted-foreground">Teléfono</p>
                    <p className="text-sm">{doctor.phone}</p>
                  </div>
                </div>

                {doctor.officePhone && (
                  <div className="flex items-start gap-3">
                    <Building2 className="w-4 h-4 text-muted-foreground mt-1" />
                    <div>
                      <p className="text-xs text-muted-foreground">Teléfono consultorio</p>
                      <p className="text-sm">{doctor.officePhone}</p>
                    </div>
                  </div>
                )}

                {doctor.address && (
                  <div className="flex items-start gap-3">
                    <MapPin className="w-4 h-4 text-muted-foreground mt-1" />
                    <div>
                      <p className="text-xs text-muted-foreground">Dirección consultorio</p>
                      <p className="text-sm">{doctor.address}</p>
                      <p className="text-xs text-muted-foreground mt-1">
                        {doctor.city}, {doctor.country}
                      </p>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Horarios de atención */}
            {doctor.schedule && doctor.schedule.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Clock className="w-4 h-4" />
                    Horarios de atención
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    {doctor.schedule.map((schedule: any, index: number) => (
                      <div key={index} className="flex justify-between items-center py-2 border-b last:border-b-0">
                        <span className="text-sm">{schedule.days}</span>
                        <span className="text-sm text-muted-foreground">{schedule.hours}</span>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}
          </TabsContent>

          {/* Tab Profesional */}
          <TabsContent value="professional" className="space-y-4 mt-4">
            {/* Información académica */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <GraduationCap className="w-4 h-4" />
                  Formación académica
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="flex items-start gap-3">
                  <Stethoscope className="w-4 h-4 text-muted-foreground mt-1" />
                  <div>
                    <p className="text-xs text-muted-foreground">Especialidad principal</p>
                    <p className="text-sm">{doctor.specialty}</p>
                  </div>
                </div>

                {doctor.subspecialties && doctor.subspecialties.length > 0 && (
                  <div className="flex items-start gap-3">
                    <Award className="w-4 h-4 text-muted-foreground mt-1" />
                    <div>
                      <p className="text-xs text-muted-foreground">Subespecialidades</p>
                      <div className="flex flex-wrap gap-1 mt-1">
                        {doctor.subspecialties.map((sub: string, index: number) => (
                          <Badge key={index} variant="outline" className="text-xs">
                            {sub}
                          </Badge>
                        ))}
                      </div>
                    </div>
                  </div>
                )}

                {doctor.university && (
                  <div className="flex items-start gap-3">
                    <GraduationCap className="w-4 h-4 text-muted-foreground mt-1" />
                    <div>
                      <p className="text-xs text-muted-foreground">Universidad</p>
                      <p className="text-sm">{doctor.university}</p>
                    </div>
                  </div>
                )}

                {doctor.graduationYear && (
                  <div className="flex items-start gap-3">
                    <Calendar className="w-4 h-4 text-muted-foreground mt-1" />
                    <div>
                      <p className="text-xs text-muted-foreground">Año de graduación</p>
                      <p className="text-sm">{doctor.graduationYear}</p>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Licencias y certificaciones */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Shield className="w-4 h-4" />
                  Licencias y certificaciones
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="flex items-start gap-3">
                  <FileText className="w-4 h-4 text-muted-foreground mt-1" />
                  <div>
                    <p className="text-xs text-muted-foreground">Número de licencia médica</p>
                    <p className="text-sm">{doctor.licenseNumber}</p>
                  </div>
                </div>

                {doctor.licenseExpiry && (
                  <div className="flex items-start gap-3">
                    <Calendar className="w-4 h-4 text-muted-foreground mt-1" />
                    <div>
                      <p className="text-xs text-muted-foreground">Vencimiento de licencia</p>
                      <p className="text-sm">{doctor.licenseExpiry}</p>
                    </div>
                  </div>
                )}

                {doctor.certifications && doctor.certifications.length > 0 && (
                  <div className="flex items-start gap-3">
                    <Award className="w-4 h-4 text-muted-foreground mt-1" />
                    <div className="flex-1">
                      <p className="text-xs text-muted-foreground mb-2">Certificaciones adicionales</p>
                      <div className="space-y-2">
                        {doctor.certifications.map((cert: string, index: number) => (
                          <div key={index} className="flex items-center gap-2 p-2 bg-blue-50 rounded-md border border-blue-200">
                            <CheckCircle2 className="w-3 h-3 text-blue-600" />
                            <span className="text-xs">{cert}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Experiencia */}
            {doctor.yearsOfExperience && (
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Briefcase className="w-4 h-4" />
                    Experiencia profesional
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center gap-3">
                    <div className="w-12 h-12 rounded-full bg-purple-100 flex items-center justify-center">
                      <span className="text-lg text-purple-600">{doctor.yearsOfExperience}</span>
                    </div>
                    <div>
                      <p className="text-sm">Años de experiencia</p>
                      <p className="text-xs text-muted-foreground">En ejercicio profesional</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            )}
          </TabsContent>

          {/* Tab Actividad */}
          <TabsContent value="activity" className="space-y-4 mt-4">
            {/* Estadísticas de prescripción */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <BarChart3 className="w-4 h-4" />
                  Estadísticas de prescripción
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-muted-foreground">Total de recetas emitidas</span>
                    <span className="text-sm">{doctor.totalPrescriptions || 0}</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-muted-foreground">Recetas este mes</span>
                    <span className="text-sm">{doctor.monthlyPrescriptions || 0}</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-muted-foreground">Pacientes únicos</span>
                    <span className="text-sm">{doctor.totalPatients || 0}</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-muted-foreground">Promedio mensual</span>
                    <span className="text-sm">
                      {doctor.averageMonthlyPrescriptions || 0} recetas/mes
                    </span>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Información del sistema */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <ClipboardList className="w-4 h-4" />
                  Información del sistema
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="flex justify-between items-center">
                  <span className="text-sm text-muted-foreground">Fecha de registro</span>
                  <span className="text-sm">{doctor.registrationDate}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-muted-foreground">Última actividad</span>
                  <span className="text-sm">{doctor.lastActivity}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-muted-foreground">ID del sistema</span>
                  <span className="text-sm text-muted-foreground">{doctor.id}</span>
                </div>
              </CardContent>
            </Card>

            {/* Alertas o notas */}
            {doctor.notes && (
              <Card className="border-orange-200 bg-orange-50/50">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-orange-800">
                    <AlertTriangle className="w-4 h-4" />
                    Notas administrativas
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-orange-900">{doctor.notes}</p>
                </CardContent>
              </Card>
            )}
          </TabsContent>
        </Tabs>

        {/* Botones de acción */}
        <div className="mt-6 pt-6 border-t flex gap-2">
          <Button
            variant="outline"
            className="flex-1"
            onClick={() => setIsEditDialogOpen(true)}
          >
            <Edit className="w-4 h-4 mr-2" />
            Editar médico
          </Button>
          <Button 
            variant="outline" 
            className="flex-1"
            onClick={() => {
              if (onViewPrescriptions) {
                onViewPrescriptions(doctor.id);
                onClose();
              }
            }}
          >
            <FileText className="w-4 h-4 mr-2" />
            Ver recetas
          </Button>
        </div>
      </SheetContent>

      {/* Diálogo de edición */}
      <EditDoctorDialog
        open={isEditDialogOpen}
        onOpenChange={setIsEditDialogOpen}
        doctor={doctor}
      />
    </Sheet>
  );
}
