// eprescription-frontend/src/app/components/medicine-table/medicine-table.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TableComponent, TableHeaderComponent, TableBodyComponent, TableRowComponent, TableHeadComponent, TableCellComponent } from '../ui/table/table.component';
import { Medicine } from '../add-medicine-dialog/add-medicine-dialog.component';

@Component({
  selector: 'app-medicine-table',
  standalone: true,
  imports: [
    CommonModule,
    TableComponent,
    TableHeaderComponent,
    TableBodyComponent,
    TableRowComponent,
    TableHeadComponent,
    TableCellComponent
  ],
  template: `
    <div class="border rounded-lg">
      <app-table>
        <app-table-header>
          <app-table-row>
            <app-table-head>Medicamento</app-table-head>
            <app-table-head>Cantidad</app-table-head>
            <app-table-head>Dosis</app-table-head>
            <app-table-head>Frecuencia</app-table-head>
            <app-table-head>Vía de Administración</app-table-head>
            <app-table-head>Duración</app-table-head>
          </app-table-row>
        </app-table-header>
        <app-table-body>
          <app-table-row 
            *ngFor="let medicine of medicines"
            class="cursor-pointer hover:bg-gray-50 transition-colors"
            (dblclick)="onMedicineDoubleClick(medicine)"
            title="Doble clic para ver detalles"
          >
            <app-table-cell class="font-medium">{{ medicine.name }}</app-table-cell>
            <app-table-cell>{{ medicine.quantity }}</app-table-cell>
            <app-table-cell>{{ medicine.dose }}</app-table-cell>
            <app-table-cell>{{ medicine.frequency }}</app-table-cell>
            <app-table-cell>{{ medicine.administration }}</app-table-cell>
            <app-table-cell>{{ medicine.duration }}</app-table-cell>
          </app-table-row>
          <app-table-row *ngIf="medicines.length === 0">
            <app-table-cell colspan="6" class="text-center text-gray-500 py-8">
              No hay medicamentos agregados
            </app-table-cell>
          </app-table-row>
        </app-table-body>
      </app-table>
    </div>
  `
})
export class MedicineTableComponent {
  @Input() medicines: Medicine[] = [];
  @Output() medicineDoubleClick = new EventEmitter<Medicine>();

  onMedicineDoubleClick(medicine: Medicine) {
    this.medicineDoubleClick.emit(medicine);
  }
}

// ePrescription-react/src/components/MedicineTable.tsx
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "./ui/table";

export interface Medicine {
  id: string;
  name: string;
  quantity: string;
  dose: string;
  frequency: string;
  administration: string;
  duration: string;
  observations?: string;
}

interface MedicineTableProps {
  medicines: Medicine[];
  onMedicineDoubleClick: (medicine: Medicine) => void;
}

export function MedicineTable({ medicines, onMedicineDoubleClick }: MedicineTableProps) {
  return (
    <div className="border rounded-lg">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Medicamento</TableHead>
            <TableHead>Cantidad</TableHead>
            <TableHead>Dosis</TableHead>
            <TableHead>Frecuencia</TableHead>
            <TableHead>Vía de Administración</TableHead>
            <TableHead>Duración</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {medicines.map((medicine) => (
            <TableRow 
              key={medicine.id}
              className="cursor-pointer hover:bg-muted/50 transition-colors"
              onDoubleClick={() => onMedicineDoubleClick(medicine)}
              title="Doble clic para ver detalles"
            >
              <TableCell className="font-medium">{medicine.name}</TableCell>
              <TableCell>{medicine.quantity}</TableCell>
              <TableCell>{medicine.dose}</TableCell>
              <TableCell>{medicine.frequency}</TableCell>
              <TableCell>{medicine.administration}</TableCell>
              <TableCell>{medicine.duration}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}
